---
  -  name: Basic Juniper ansible demo
     hosts: MX 
     gather_facts: no
     tasks:
       -  name: Pulling show version 
          junipernetworks.junos.junos_command:
            commands:
              -  show version
            display: text
          register: output 

       - name: Display output 
         debug:
           msg: "{{output}}"
                
          
    
  
