---
  - name: Demo on config and jinjaj2 template
    hosts: MX
    gather_facts: no
    vars:
      ansible_connection: netconf
      ansible_network_os: junipernetworks.junos.junos

    tasks:
      - name: backup directory
        file:
          path: "{{playbook_dir}}/../config_back1/{{inventory_hostname}}"
          state: directory
          mode: '0755'
        delegate_to: localhost
      - name: Render the template to a temporary file
        template:
          src: ../templates/Juniper_device_basic_configuration.j2
          dest: "{{playbook_dir}}/../config_back1/{{inventory_hostname}}/{{inventory_hostname}}_rendered_config.txt"
        delegate_to: localhost

      - name: Load the rendered config to juniper device
        junipernetworks.junos.junos_config:
          src:   "{{playbook_dir}}/../config_back1/{{inventory_hostname}}/MX_rendered_config.txt
          comment: Push render config to device
