---
  - name: Demo on config and jinjaj2 template
    hosts: MX
    gather_facts: no
    vars:
      ansible_connection: netconf
      ansible_network_os: junipernetworks.junos.junos

    tasks:
      - name: Render the template to a temporary file
        template:
          src: ../templates/Juniper_device_basic_configuration.j2
          dest: "https://github.com/ashishsh30/Network_automation/tree/eed5c7cfaae4606d1b7cec61226ce8e94b32c609/Playbook/config_backup/{{inventory_hostname}}_rendered_config.txt"

      - name: Load the rendered config to juniper device
        junipernetworks.junos.junos_config:
          src:   "https://github.com/ashishsh30/Network_automation/tree/eed5c7cfaae4606d1b7cec61226ce8e94b32c609/Playbook/config_backup/MX_rendered_config.txt"
          comment: Push render config to device
